### ISSUE TITLE
Incorrect error response to successful 'code' sign-up

### ISSUE THREAD

**Issue by Lanzafame** [codenetwork/CodeNetwork.co#1]
<img width="604" alt="screen shot 2016-02-23 at 1 23 44 pm" src="https://cloud.githubusercontent.com/assets/5924712/13240883/0ca92edc-da32-11e5-99d5-6bf60be9a751.png">
When payment option is set to 'code', a successfully processed signup (alert confirms this), the above message appears.

**Comment by trjstewart** [comment]
This was a bug in the preceeding PHP version of the codenetwork.co user registration and isn't applicable to this repo.

**Comment by Lanzafame** [comment]
:+1:
